### ISSUE TITLE
error

### ISSUE THREAD

**Issue by M1R1ZAL1** [7zx/overload#16]
error page

**Comment by alboms** [comment]
CriticalError("Falha ao importar alguns modulos", err)
NameError: name 'CriticalError' is not defined


some modules couldnt be imported idk what to do now

**Comment by 7zx** [comment]
hi, sorry for the late answer, you just gotta download all the modules left

**Comment by 8fn** [comment]
> CriticalError("Falha ao importar alguns modulos", err) NameError: name 'CriticalError' is not defined
> 
> some modules couldnt be imported idk what to do now

Had the same problem, run with python instead of python3
