### ISSUE TITLE
Bug termux

### ISSUE THREAD

**Issue by Jeiel17** [7zx/overload#39]
```
ERROR: Could not find a version that satisfies the requirement ctypes (from versions: none)
ERROR: No matching distribution found for ctypes
```

Termux version: 0.118.0

**Comment by 8fn** [comment]
We removed ctypes
Update overload by trying to do 
`git pull origin main`

**Comment by 8fn** [comment]
> ```
> ERROR: Could not find a version that satisfies the requirement ctypes (from versions: none)
> ERROR: No matching distribution found for ctypes
> ```
> 
> Termux version: 0.118.0

Já removi o ctypes no código, atualiza o overload com `git pull origin main` ou faz git clone outra vez
