### ISSUE TITLE
Start Program BUG!

### ISSUE THREAD

**Issue by ceedledev** [7zx/overload#45]
<img width="493" alt="Capture" src="https://user-images.githubusercontent.com/82039844/193418706-c80dda57-c967-4f11-bb60-d398ca7df250.PNG">

**Comment by 8fn** [comment]
Update repository by doing `git pull origin main` or redo delete your current overload and clone repository again

**Comment by joao-vitor-souza** [comment]
You're using ASCII as your python default encoder, try add `# -*- coding: utf-8 -*-` at the top of your `overload.py` file, doing so utf-8 enconding will do the job.

@8fn , apply this [commit](https://github.com/7zx/overload/commit/26a6f6a0c1e683b64d802706e8db147e36a903e0) again.

**Comment by ceedledev** [comment]
<img width="494" alt="Capture" src="https://user-images.githubusercontent.com/82039844/193420420-d3395661-e0f2-43ba-aaec-86b2930ffd59.PNG">

**Comment by joao-vitor-souza** [comment]
> <img alt="Capture" width="494" src="https://user-images.githubusercontent.com/82039844/193420420-d3395661-e0f2-43ba-aaec-86b2930ffd59.PNG">

Just ran it here and it works great. That's weird, `time = int(input(f"{Fore.RED}│   ├───TIME:{Fore.RESET}"))` doesn't actually have a SyntaxError. Has `colorama` been installed correctly? Maybe is it something with `Fore` class?

**Comment by 8fn** [comment]
> <img alt="Capture" width="494" src="https://user-images.githubusercontent.com/82039844/193420420-d3395661-e0f2-43ba-aaec-86b2930ffd59.PNG">

Here works great, try to clone again overload

**Comment by 8fn** [comment]
What is your python version?
Try to run python3
![image](https://user-images.githubusercontent.com/47666341/193445672-5aebd838-d5b9-4c5b-a467-e1403e4bb013.png)

**Comment by 8fn** [comment]
> <img alt="Capture" width="494" src="https://user-images.githubusercontent.com/82039844/193420420-d3395661-e0f2-43ba-aaec-86b2930ffd59.PNG">

I just checked and it doesnt work with python2
![image](https://user-images.githubusercontent.com/47666341/193676987-135ada96-e57d-4eec-ad50-55c379e81d52.png)

Try to run with python3
