### ISSUE TITLE
im booting sites but they wont go down

### ISSUE THREAD

**Issue by 1907amk** [7zx/overload#61]
as the title says  i boot them but they wont go down  and they also wont slow down  help me pls

[Screen recording 2022-11-29 16.34.07.webm](https://user-images.githubusercontent.com/106609714/204573061-9b4fc9e1-c98e-4395-8716-af484729f755.webm)

**Comment by 1907amk** [comment]
im on linux btw

**Comment by 7zx** [comment]
The attack will not be effective on all websites, it depends a lot on whether they have a good host or a bad host.

**Comment by joao-vitor-souza** [comment]
Notice that most websites today use load balancers to mitigate DDoS attacks. Strictly speaking, Overload is a DoS attack as it simulates many requests using threads, not actual machines, with their own MAC address, IP, resources, and so on. So it'll probably fail to get robust sites down; however, it can easily get local servers down. Also, as @7zx said, your hardware and bandwidth are also limitations, so you'll need to run Overload at the same time, on multiple devices, to actually make a DDoS attack successful. That's what a botnet does.

**Comment by 1907amk** [comment]
does  it matter how many devices i use  and how many threads does it take to take a site down

**Comment by joao-vitor-souza** [comment]
> does it matter how many devices i use and how many threads does it take to take a site down

Of course, the number of threads and their proper functioning is limited by your hardware, and the only way to bypass this is by coordinately running Overload on many devices; for a small or bad hosted server, Overload will work just fine. If you wanna discuss more about this topic, consider entering our [Discord Server](https://discord.gg/rPx2MWQg).
